# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend/

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Create Secrets File Action
      uses: du5rte/create-secrets-file@v1
      with:
        secrets: |
          PGHOST=${{ secrets.PGHOST }}
          PGDATABASE=${{ secrets.PGDATABASE }}
          PGUSER=${{ secrets.PGUSER }}
          PGPASSWORD=${{ secrets.PGPASSWORD }}
          ENDPOINT_ID=${{ secrets.ENDPOINT_ID }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      # env:
      #   PGHOST: ${{ secrets.PGHOST }}
      #   PGDATABASE: ${{ secrets.PGDATABASE }}
      #   PGUSER: ${{ secrets.PGUSER }}
      #   PGPASSWORD: ${{ secrets.PGPASSWORD }}
      #   ENDPOINT_ID: ${{ secrets.ENDPOINT_ID }}
      #   GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      #   GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './src/backend/package-lock.json'
    - run: npm ci
    - run: npm start
    # - run: npm test
